# docker/Dockerfile.api

FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the API part of the app
COPY app/ app/

# Expose port used by Uvicorn
EXPOSE 8000

# Start the API server
CMD ["uvicorn", "app.mock_device_server:app", "--host", "0.0.0.0", "--port", "8000"]
